### ISSUE TITLE
jquery-ui dependency breaks custom builds/ latest jquery UI

### ISSUE THREAD

**Issue by jrhe** [Addepar/ember-table-addon#12]
Using a custom build of jquery-ui or the latest version (~1.11.4) doesn't work using the add on as it 

Currently the addon expects a file located in `app.bowerDirectory + '/jquery-ui/jquery-ui.js'`. With a custom build of jquery ui or the default bower package for version (~1.11.4) don't have this file and instead have `/jquery-ui/ui/jquery-ui.custom.js`.

What is this jquery-ui used for? Not sure I have seen it used in the codebase other than for examples.

Perhaps there is a better way of importing it.

**Comment by azirbel** [comment]
We use jquery-ui for column reordering/resizing, so it's necessary.

Are you sure you've installed the right version? `bower.json` requires `^1.11.1`, and my local version `1.11.4` does have `'/jquery-ui/jquery-ui.js'`.

**Comment by jrhe** [comment]
Ahh right I see. It's odd as I had something which purported to be 1.11.4 before which didn't have the files but if I delete the folder and then re-install with ^1.11.1 in my bower.json it works.

Closing for now.
