### ISSUE TITLE
Should new features be added here or in ember-table?

### ISSUE THREAD

**Issue by BryanCrotaz** [Addepar/ember-table-addon#14]
Is ember-table going to be merged with ember-table-addon or is this a replacement?

Where should I add new features?

**Comment by azirbel** [comment]
Yes, it'll be merged - see https://github.com/Addepar/ember-table/pull/309.

We're currently blocked on a memory leak that appears during testing. Once we resolve that, we'll merge and shut down this repository.

In the meantime, add features here. I'll port them over to the main repo once that pull request is complete.
