### ISSUE TITLE
Not published to NPM?

### ISSUE THREAD

**Issue by bryanaka** [Addepar/ember-table-addon#2]
Is this ready to be used in prod at all? 

I saw @azirbel (thanks for speaking btw :+1: ) present on this conversion process yesterday and was under the impression that is was usable, just not truly converted over to ES6 modules yet.

**Comment by azirbel** [comment]
Ah, I gave the wrong impression. Sorry @bryanaka! I'm still porting code and want to be more sure that everything works before I'm ready to publish to npm. Fingers crossed, I'll be able to publish/start using the new code by the end of the week.

In the meantime, you can use @intuitivepixel's version: https://github.com/intuitivepixel/ember-cli-ember-table.

**Comment by bryanaka** [comment]
looks like @intuitivepixel is helping in the conversion so im guessing the switch, when it happens, shouldn't be too painful.

Thanks @azirbel!

**Comment by sedovalx** [comment]
Is it right that the package is still absent? How it goes? I'm really looking forward to use this amazing grid! 
Btw: why are you moving from CoffeScript to JavaScript?

**Comment by bryanaka** [comment]
@sedovalx I might be wrong on this, but from what I understand, they are moving it from CoffeeScript to JavaScript because:

1. Ember-CLI uses Babel to precompile ES6 features, including modules, the fat arrow function, etc. In CoffeeScript, you have to use back ticks to  take advantage of these features, which is a bit annoying.
2. Everyone the writes CoffeeScript knows JavaScript (ideally). The inverse isn't true.

**Comment by sedovalx** [comment]
Indeed there is Babel addon to the ember-cli. @bryanaka thank you for that! @azirbel can you say anything about the release date? @intuitivepixel's port seems to be abandoned by it's author.

**Comment by taylorjames** [comment]
Any word on when the package will be available?

**Comment by azirbel** [comment]
I have been consistently wrong when estimating this. Best I can say is to take a look at the phases in the README of this repository, and follow along with the commits here. Current work is on a branch: https://github.com/Addepar/ember-table-addon/tree/azirbel/convert-src. I'm hoping to publish to npm within this week, but I'm not able to remotely guarantee it.

intuitivepixel's port has been a great temporary solution. Another workaround for now is to import ember-table normally via bower. https://github.com/azirbel/minipar is an example, and ember-table branches exist for Ember 1.9 and 1.10.

@bryanaka's answer on moving to JS is correct; you can find much more detail if you search the ember-table issues.

**Comment by sedovalx** [comment]
@azirbel that's what I need, thank you for the example!
