### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by taylorjames** [Addepar/ember-table-addon#4]
Many deprecations relating to global lookup of views. http://emberjs.com/guides/deprecations/#toc_global-lookup-of-views-since-1-8

Are these deprecations being looked at?

**Comment by azirbel** [comment]
this repository is a work in progress - so, yes!

**Comment by taylorjames** [comment]
Any sort of ETA on when the view lookups can be changed? I can help change the view lookup to get rid of the deprecations if needed.

**Comment by azirbel** [comment]
I'm currently working on it in my branch https://github.com/Addepar/ember-table-addon/tree/azirbel/convert-src. I just removed some but may have missed others.

If you want to help out with this effort, the most helpful thing to do would be to submit small, targeted PRs to address anything marked `FIXME` on the master branch.

**Comment by azirbel** [comment]
I believe this should be fixed on master; check it out if you want! I'm considering this resolved and will close it. Please reopen if you find it's still a problem.
